version: "3"

services:
  blink:
    image: sidntrivedi012/blink
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDRESS=redis-server:6379
      - APP_PORT=8080

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    container_name: redis-server
    volumes:
      - ./data:/data
    ports:
      - '6379:6379'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes